### ISSUE TITLE
improve the readme.md

### ISSUE THREAD

**Issue by karthiknadar1204** [upes-open/near-me#16]
Here i propose to make the readme elaborate by adding an elaborate way to open a pr and set up the project as well as shell commands so that anyone starting out with the project can start out easily

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by saarinii** [comment]
Hey Karthik ! Updating the README.md is not a feature solving in the project. The readme is already designed by our heads, also the documentation will be done at the last of the OSoC'23.
Updating the README.md will contain the UI screenshots, brief features of project.

**Comment by karthiknadar1204** [comment]
So what will i be adding to the readme for now could you please elaborate, also please reconfirm if this issue for documentation will be considered for points @saarinii

**Comment by saarinii** [comment]
You can add UI screenshots, brief features of the project, etc but do not change the format of it. Yes it will be counted a issue of easy category

**Comment by karthiknadar1204** [comment]
But the project doesn't seem to have been initialized yet

**Comment by saarinii** [comment]
Then you'd have to wait till it does
